// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../messenger/jupiter/interface.go

// Package mock_jupiter is a generated GoMock package.
package mock_jupiter

import (
	context "context"
	reflect "reflect"

	solana "github.com/gagliardetto/solana-go"
	token "github.com/gagliardetto/solana-go/programs/token"
	rpc "github.com/gagliardetto/solana-go/rpc"
	gomock "github.com/golang/mock/gomock"
	jupiter "github.com/structured-org/aum-messenger/pkg/client/jupiter"
	neutron "github.com/structured-org/aum-messenger/pkg/client/neutron"
)

// MockJupiterClient is a mock of JupiterClient interface.
type MockJupiterClient struct {
	ctrl     *gomock.Controller
	recorder *MockJupiterClientMockRecorder
}

// MockJupiterClientMockRecorder is the mock recorder for MockJupiterClient.
type MockJupiterClientMockRecorder struct {
	mock *MockJupiterClient
}

// NewMockJupiterClient creates a new mock instance.
func NewMockJupiterClient(ctrl *gomock.Controller) *MockJupiterClient {
	mock := &MockJupiterClient{ctrl: ctrl}
	mock.recorder = &MockJupiterClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJupiterClient) EXPECT() *MockJupiterClientMockRecorder {
	return m.recorder
}

// GetJupiterCustodyInfo mocks base method.
func (m *MockJupiterClient) GetJupiterCustodyInfo(ctx context.Context, custody solana.PublicKey) (*jupiter.JupiterPerpsCustodyAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJupiterCustodyInfo", ctx, custody)
	ret0, _ := ret[0].(*jupiter.JupiterPerpsCustodyAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJupiterCustodyInfo indicates an expected call of GetJupiterCustodyInfo.
func (mr *MockJupiterClientMockRecorder) GetJupiterCustodyInfo(ctx, custody interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJupiterCustodyInfo", reflect.TypeOf((*MockJupiterClient)(nil).GetJupiterCustodyInfo), ctx, custody)
}

// GetJupiterPoolInfo mocks base method.
func (m *MockJupiterClient) GetJupiterPoolInfo(ctx context.Context, pool solana.PublicKey) (*jupiter.JupiterPoolAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJupiterPoolInfo", ctx, pool)
	ret0, _ := ret[0].(*jupiter.JupiterPoolAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJupiterPoolInfo indicates an expected call of GetJupiterPoolInfo.
func (mr *MockJupiterClientMockRecorder) GetJupiterPoolInfo(ctx, pool interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJupiterPoolInfo", reflect.TypeOf((*MockJupiterClient)(nil).GetJupiterPoolInfo), ctx, pool)
}

// MockSolanaClient is a mock of SolanaClient interface.
type MockSolanaClient struct {
	ctrl     *gomock.Controller
	recorder *MockSolanaClientMockRecorder
}

// MockSolanaClientMockRecorder is the mock recorder for MockSolanaClient.
type MockSolanaClientMockRecorder struct {
	mock *MockSolanaClient
}

// NewMockSolanaClient creates a new mock instance.
func NewMockSolanaClient(ctrl *gomock.Controller) *MockSolanaClient {
	mock := &MockSolanaClient{ctrl: ctrl}
	mock.recorder = &MockSolanaClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSolanaClient) EXPECT() *MockSolanaClientMockRecorder {
	return m.recorder
}

// GetNativeBalance mocks base method.
func (m *MockSolanaClient) GetNativeBalance(ctx context.Context, account solana.PublicKey) (*rpc.UiTokenAmount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNativeBalance", ctx, account)
	ret0, _ := ret[0].(*rpc.UiTokenAmount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNativeBalance indicates an expected call of GetNativeBalance.
func (mr *MockSolanaClientMockRecorder) GetNativeBalance(ctx, account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNativeBalance", reflect.TypeOf((*MockSolanaClient)(nil).GetNativeBalance), ctx, account)
}

// GetTokenAccountBalance mocks base method.
func (m *MockSolanaClient) GetTokenAccountBalance(ctx context.Context, token, account solana.PublicKey) (*rpc.UiTokenAmount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenAccountBalance", ctx, token, account)
	ret0, _ := ret[0].(*rpc.UiTokenAmount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenAccountBalance indicates an expected call of GetTokenAccountBalance.
func (mr *MockSolanaClientMockRecorder) GetTokenAccountBalance(ctx, token, account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenAccountBalance", reflect.TypeOf((*MockSolanaClient)(nil).GetTokenAccountBalance), ctx, token, account)
}

// GetTokenMint mocks base method.
func (m *MockSolanaClient) GetTokenMint(ctx context.Context, tokenPubKey solana.PublicKey) (*token.Mint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenMint", ctx, tokenPubKey)
	ret0, _ := ret[0].(*token.Mint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenMint indicates an expected call of GetTokenMint.
func (mr *MockSolanaClientMockRecorder) GetTokenMint(ctx, tokenPubKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenMint", reflect.TypeOf((*MockSolanaClient)(nil).GetTokenMint), ctx, tokenPubKey)
}

// MockNeutronAumReceiverClient is a mock of NeutronAumReceiverClient interface.
type MockNeutronAumReceiverClient struct {
	ctrl     *gomock.Controller
	recorder *MockNeutronAumReceiverClientMockRecorder
}

// MockNeutronAumReceiverClientMockRecorder is the mock recorder for MockNeutronAumReceiverClient.
type MockNeutronAumReceiverClientMockRecorder struct {
	mock *MockNeutronAumReceiverClient
}

// NewMockNeutronAumReceiverClient creates a new mock instance.
func NewMockNeutronAumReceiverClient(ctrl *gomock.Controller) *MockNeutronAumReceiverClient {
	mock := &MockNeutronAumReceiverClient{ctrl: ctrl}
	mock.recorder = &MockNeutronAumReceiverClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNeutronAumReceiverClient) EXPECT() *MockNeutronAumReceiverClientMockRecorder {
	return m.recorder
}

// GetJupiterAumReceiverNextRound mocks base method.
func (m *MockNeutronAumReceiverClient) GetJupiterAumReceiverNextRound(ctx context.Context) (*neutron.NextRound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJupiterAumReceiverNextRound", ctx)
	ret0, _ := ret[0].(*neutron.NextRound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJupiterAumReceiverNextRound indicates an expected call of GetJupiterAumReceiverNextRound.
func (mr *MockNeutronAumReceiverClientMockRecorder) GetJupiterAumReceiverNextRound(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJupiterAumReceiverNextRound", reflect.TypeOf((*MockNeutronAumReceiverClient)(nil).GetJupiterAumReceiverNextRound), ctx)
}

// SubmitJupiterAumData mocks base method.
func (m *MockNeutronAumReceiverClient) SubmitJupiterAumData(ctx context.Context, data *neutron.JupiterAumData) (*neutron.NextRound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitJupiterAumData", ctx, data)
	ret0, _ := ret[0].(*neutron.NextRound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitJupiterAumData indicates an expected call of SubmitJupiterAumData.
func (mr *MockNeutronAumReceiverClientMockRecorder) SubmitJupiterAumData(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitJupiterAumData", reflect.TypeOf((*MockNeutronAumReceiverClient)(nil).SubmitJupiterAumData), ctx, data)
}
