version: "3.8"

services:
  aum-messenger:
    build:
      context: .
      dockerfile: Dockerfile.aum_messenger
    container_name: aum-messenger
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    command: ["--config", "/app/config.yaml"]

  recorder:
    build:
      context: .
      dockerfile: Dockerfile.recorder
    container_name: recorder
    volumes:
      - ./recorder/config.yaml:/app/config.yaml:ro
    command: ["--config", "/app/config.yaml"]

  safe-relay:
    build:
      context: .
      dockerfile: Dockerfile.safe_relay
    container_name: safe-relay
    volumes:
      - ./safe_relay/config.toml:/app/config.toml:ro
    command: [""]
