version: '3.8'

services:
  aum-messenger:
    build:
      context: aum_messenger
      dockerfile: aum_messenger/Dockerfile
    container_name: aum-messenger
    volumes:
      - ./config.yaml:/aum_messenger/config.yaml:ro
    command: ["--config", "/aum_messenger/config.yaml"]
