[package]
authors = []
description = "Neutron Jupiter AUM Oracle Receiver contract"
edition = "2021"
name = "jupiter-aum-receiver"
repository = "https://github.com/structured-org/aum-oracle"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-schema = { version = "2.2.0" }
cosmwasm-std = { version = "2.2.2" }
cw-storage-plus = "2.0.0"
cw2 = "2.0.0"
neutron-std = { git = "https://github.com/neutron-org/neutron-std.git", branch = "main" }
jupiter-aum-common = { path = "../../packages/jupiter-aum-common" }
aum-receiver-common = { path = "../../packages/aum-receiver-common" }
consensus = { path = "../../packages/consensus" }
