// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../binance/interface.go

// Package mock_binance is a generated GoMock package.
package mock_binance

import (
	context "context"
	reflect "reflect"

	binance "github.com/adshao/go-binance/v2"
	portfolio "github.com/adshao/go-binance/v2/portfolio"
	gomock "github.com/golang/mock/gomock"
	neutron "github.com/structured-org/aum-oracle/client/neutron"
)

// MockBinanceClient is a mock of BinanceClient interface.
type MockBinanceClient struct {
	ctrl     *gomock.Controller
	recorder *MockBinanceClientMockRecorder
}

// MockBinanceClientMockRecorder is the mock recorder for MockBinanceClient.
type MockBinanceClientMockRecorder struct {
	mock *MockBinanceClient
}

// NewMockBinanceClient creates a new mock instance.
func NewMockBinanceClient(ctrl *gomock.Controller) *MockBinanceClient {
	mock := &MockBinanceClient{ctrl: ctrl}
	mock.recorder = &MockBinanceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBinanceClient) EXPECT() *MockBinanceClientMockRecorder {
	return m.recorder
}

// GetCmPositions mocks base method.
func (m *MockBinanceClient) GetCmPositions(ctx context.Context) ([]*portfolio.CMPosition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCmPositions", ctx)
	ret0, _ := ret[0].([]*portfolio.CMPosition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCmPositions indicates an expected call of GetCmPositions.
func (mr *MockBinanceClientMockRecorder) GetCmPositions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCmPositions", reflect.TypeOf((*MockBinanceClient)(nil).GetCmPositions), ctx)
}

// GetPMAccountBalance mocks base method.
func (m *MockBinanceClient) GetPMAccountBalance(ctx context.Context) ([]*portfolio.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPMAccountBalance", ctx)
	ret0, _ := ret[0].([]*portfolio.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPMAccountBalance indicates an expected call of GetPMAccountBalance.
func (mr *MockBinanceClientMockRecorder) GetPMAccountBalance(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPMAccountBalance", reflect.TypeOf((*MockBinanceClient)(nil).GetPMAccountBalance), ctx)
}

// GetPMAccountInfo mocks base method.
func (m *MockBinanceClient) GetPMAccountInfo(ctx context.Context) (*portfolio.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPMAccountInfo", ctx)
	ret0, _ := ret[0].(*portfolio.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPMAccountInfo indicates an expected call of GetPMAccountInfo.
func (mr *MockBinanceClientMockRecorder) GetPMAccountInfo(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPMAccountInfo", reflect.TypeOf((*MockBinanceClient)(nil).GetPMAccountInfo), ctx)
}

// GetSpotAccountInfo mocks base method.
func (m *MockBinanceClient) GetSpotAccountInfo(ctx context.Context) (*binance.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpotAccountInfo", ctx)
	ret0, _ := ret[0].(*binance.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpotAccountInfo indicates an expected call of GetSpotAccountInfo.
func (mr *MockBinanceClientMockRecorder) GetSpotAccountInfo(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpotAccountInfo", reflect.TypeOf((*MockBinanceClient)(nil).GetSpotAccountInfo), ctx)
}

// GetUmPositions mocks base method.
func (m *MockBinanceClient) GetUmPositions(ctx context.Context) ([]*portfolio.UMPosition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUmPositions", ctx)
	ret0, _ := ret[0].([]*portfolio.UMPosition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUmPositions indicates an expected call of GetUmPositions.
func (mr *MockBinanceClientMockRecorder) GetUmPositions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUmPositions", reflect.TypeOf((*MockBinanceClient)(nil).GetUmPositions), ctx)
}

// MockNeutronClient is a mock of NeutronClient interface.
type MockNeutronClient struct {
	ctrl     *gomock.Controller
	recorder *MockNeutronClientMockRecorder
}

// MockNeutronClientMockRecorder is the mock recorder for MockNeutronClient.
type MockNeutronClientMockRecorder struct {
	mock *MockNeutronClient
}

// NewMockNeutronClient creates a new mock instance.
func NewMockNeutronClient(ctrl *gomock.Controller) *MockNeutronClient {
	mock := &MockNeutronClient{ctrl: ctrl}
	mock.recorder = &MockNeutronClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNeutronClient) EXPECT() *MockNeutronClientMockRecorder {
	return m.recorder
}

// GetBinanceAumContractNextRound mocks base method.
func (m *MockNeutronClient) GetBinanceAumContractNextRound(ctx context.Context) (*neutron.NextRound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBinanceAumContractNextRound", ctx)
	ret0, _ := ret[0].(*neutron.NextRound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBinanceAumContractNextRound indicates an expected call of GetBinanceAumContractNextRound.
func (mr *MockNeutronClientMockRecorder) GetBinanceAumContractNextRound(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBinanceAumContractNextRound", reflect.TypeOf((*MockNeutronClient)(nil).GetBinanceAumContractNextRound), ctx)
}

// SubmitBinanceAumData mocks base method.
func (m *MockNeutronClient) SubmitBinanceAumData(ctx context.Context, data *neutron.BinanceData) (*neutron.NextRound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitBinanceAumData", ctx, data)
	ret0, _ := ret[0].(*neutron.NextRound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitBinanceAumData indicates an expected call of SubmitBinanceAumData.
func (mr *MockNeutronClientMockRecorder) SubmitBinanceAumData(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitBinanceAumData", reflect.TypeOf((*MockNeutronClient)(nil).SubmitBinanceAumData), ctx, data)
}
