// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../messenger/arbitrary_data/interface.go

// Package mock_arbitrary_data is a generated GoMock package.
package mock_arbitrary_data

import (
	context "context"
	reflect "reflect"

	solana "github.com/gagliardetto/solana-go"
	gomock "github.com/golang/mock/gomock"
	client "github.com/structured-org/aum-messenger/client"
)

// MockSolanaClient is a mock of SolanaClient interface.
type MockSolanaClient struct {
	ctrl     *gomock.Controller
	recorder *MockSolanaClientMockRecorder
}

// MockSolanaClientMockRecorder is the mock recorder for MockSolanaClient.
type MockSolanaClientMockRecorder struct {
	mock *MockSolanaClient
}

// NewMockSolanaClient creates a new mock instance.
func NewMockSolanaClient(ctrl *gomock.Controller) *MockSolanaClient {
	mock := &MockSolanaClient{ctrl: ctrl}
	mock.recorder = &MockSolanaClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSolanaClient) EXPECT() *MockSolanaClientMockRecorder {
	return m.recorder
}

// GetArbitraryNeutronContractDataNextRound mocks base method.
func (m *MockSolanaClient) GetArbitraryNeutronContractDataNextRound(ctx context.Context, in string, instanceKey solana.PublicKey) (*client.NextRound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArbitraryNeutronContractDataNextRound", ctx, in, instanceKey)
	ret0, _ := ret[0].(*client.NextRound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArbitraryNeutronContractDataNextRound indicates an expected call of GetArbitraryNeutronContractDataNextRound.
func (mr *MockSolanaClientMockRecorder) GetArbitraryNeutronContractDataNextRound(ctx, in, instanceKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArbitraryNeutronContractDataNextRound", reflect.TypeOf((*MockSolanaClient)(nil).GetArbitraryNeutronContractDataNextRound), ctx, in, instanceKey)
}

// SubmitArbitraryNeutronContractData mocks base method.
func (m *MockSolanaClient) SubmitArbitraryNeutronContractData(ctx context.Context, programID, instanceKey solana.PublicKey, oraclesList *[]string, data *[]byte) (*client.NextRound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitArbitraryNeutronContractData", ctx, programID, instanceKey, oraclesList, data)
	ret0, _ := ret[0].(*client.NextRound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitArbitraryNeutronContractData indicates an expected call of SubmitArbitraryNeutronContractData.
func (mr *MockSolanaClientMockRecorder) SubmitArbitraryNeutronContractData(ctx, programID, instanceKey, oraclesList, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitArbitraryNeutronContractData", reflect.TypeOf((*MockSolanaClient)(nil).SubmitArbitraryNeutronContractData), ctx, programID, instanceKey, oraclesList, data)
}

// MockNeutronClient is a mock of NeutronClient interface.
type MockNeutronClient struct {
	ctrl     *gomock.Controller
	recorder *MockNeutronClientMockRecorder
}

// MockNeutronClientMockRecorder is the mock recorder for MockNeutronClient.
type MockNeutronClientMockRecorder struct {
	mock *MockNeutronClient
}

// NewMockNeutronClient creates a new mock instance.
func NewMockNeutronClient(ctrl *gomock.Controller) *MockNeutronClient {
	mock := &MockNeutronClient{ctrl: ctrl}
	mock.recorder = &MockNeutronClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNeutronClient) EXPECT() *MockNeutronClientMockRecorder {
	return m.recorder
}

// GetOraclesList mocks base method.
func (m *MockNeutronClient) GetOraclesList(ctx context.Context, contractAddress string) (*[]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOraclesList", ctx, contractAddress)
	ret0, _ := ret[0].(*[]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOraclesList indicates an expected call of GetOraclesList.
func (mr *MockNeutronClientMockRecorder) GetOraclesList(ctx, contractAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOraclesList", reflect.TypeOf((*MockNeutronClient)(nil).GetOraclesList), ctx, contractAddress)
}

// QueryArbitraryNeutronContract mocks base method.
func (m *MockNeutronClient) QueryArbitraryNeutronContract(ctx context.Context, contract, queryStr string) (*[]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryArbitraryNeutronContract", ctx, contract, queryStr)
	ret0, _ := ret[0].(*[]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryArbitraryNeutronContract indicates an expected call of QueryArbitraryNeutronContract.
func (mr *MockNeutronClientMockRecorder) QueryArbitraryNeutronContract(ctx, contract, queryStr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryArbitraryNeutronContract", reflect.TypeOf((*MockNeutronClient)(nil).QueryArbitraryNeutronContract), ctx, contract, queryStr)
}
