[package]
authors = []
description = "Binance AUM receiver contract"
edition = "2021"
name = "binance-aum-receiver"
repository = "https://github.com/structured-org/aum-oracle"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
serde = { workspace = true }
consensus = { workspace = true }
neutron-std = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }
cw-ownable = { workspace = true }
cw2 = { workspace = true }