// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../solana/interface.go

// Package mock_solana is a generated GoMock package.
package mock_solana

import (
	context "context"
	reflect "reflect"

	solana "github.com/gagliardetto/solana-go"
	rpc "github.com/gagliardetto/solana-go/rpc"
	gomock "github.com/golang/mock/gomock"
	jupiter "github.com/structured-org/aum-oracle/client/jupiter"
	neutron "github.com/structured-org/aum-oracle/client/neutron"
)

// MockJupiterClient is a mock of JupiterClient interface.
type MockJupiterClient struct {
	ctrl     *gomock.Controller
	recorder *MockJupiterClientMockRecorder
}

// MockJupiterClientMockRecorder is the mock recorder for MockJupiterClient.
type MockJupiterClientMockRecorder struct {
	mock *MockJupiterClient
}

// NewMockJupiterClient creates a new mock instance.
func NewMockJupiterClient(ctrl *gomock.Controller) *MockJupiterClient {
	mock := &MockJupiterClient{ctrl: ctrl}
	mock.recorder = &MockJupiterClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJupiterClient) EXPECT() *MockJupiterClientMockRecorder {
	return m.recorder
}

// GetJupiterCustodyInfo mocks base method.
func (m *MockJupiterClient) GetJupiterCustodyInfo(ctx context.Context, custody solana.PublicKey) (*jupiter.JupiterPerpsCustodyAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJupiterCustodyInfo", ctx, custody)
	ret0, _ := ret[0].(*jupiter.JupiterPerpsCustodyAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJupiterCustodyInfo indicates an expected call of GetJupiterCustodyInfo.
func (mr *MockJupiterClientMockRecorder) GetJupiterCustodyInfo(ctx, custody interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJupiterCustodyInfo", reflect.TypeOf((*MockJupiterClient)(nil).GetJupiterCustodyInfo), ctx, custody)
}

// GetJupiterPoolInfo mocks base method.
func (m *MockJupiterClient) GetJupiterPoolInfo(ctx context.Context, pool solana.PublicKey) (*jupiter.JupiterPoolAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJupiterPoolInfo", ctx, pool)
	ret0, _ := ret[0].(*jupiter.JupiterPoolAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJupiterPoolInfo indicates an expected call of GetJupiterPoolInfo.
func (mr *MockJupiterClientMockRecorder) GetJupiterPoolInfo(ctx, pool interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJupiterPoolInfo", reflect.TypeOf((*MockJupiterClient)(nil).GetJupiterPoolInfo), ctx, pool)
}

// MockSolanaClient is a mock of SolanaClient interface.
type MockSolanaClient struct {
	ctrl     *gomock.Controller
	recorder *MockSolanaClientMockRecorder
}

// MockSolanaClientMockRecorder is the mock recorder for MockSolanaClient.
type MockSolanaClientMockRecorder struct {
	mock *MockSolanaClient
}

// NewMockSolanaClient creates a new mock instance.
func NewMockSolanaClient(ctrl *gomock.Controller) *MockSolanaClient {
	mock := &MockSolanaClient{ctrl: ctrl}
	mock.recorder = &MockSolanaClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSolanaClient) EXPECT() *MockSolanaClientMockRecorder {
	return m.recorder
}

// GetTokenAccountBalance mocks base method.
func (m *MockSolanaClient) GetTokenAccountBalance(ctx context.Context, token, account solana.PublicKey) (*rpc.UiTokenAmount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenAccountBalance", ctx, token, account)
	ret0, _ := ret[0].(*rpc.UiTokenAmount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenAccountBalance indicates an expected call of GetTokenAccountBalance.
func (mr *MockSolanaClientMockRecorder) GetTokenAccountBalance(ctx, token, account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenAccountBalance", reflect.TypeOf((*MockSolanaClient)(nil).GetTokenAccountBalance), ctx, token, account)
}

// GetTokenSupply mocks base method.
func (m *MockSolanaClient) GetTokenSupply(ctx context.Context, token solana.PublicKey) (*rpc.UiTokenAmount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenSupply", ctx, token)
	ret0, _ := ret[0].(*rpc.UiTokenAmount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenSupply indicates an expected call of GetTokenSupply.
func (mr *MockSolanaClientMockRecorder) GetTokenSupply(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenSupply", reflect.TypeOf((*MockSolanaClient)(nil).GetTokenSupply), ctx, token)
}

// MockNeutronClient is a mock of NeutronClient interface.
type MockNeutronClient struct {
	ctrl     *gomock.Controller
	recorder *MockNeutronClientMockRecorder
}

// MockNeutronClientMockRecorder is the mock recorder for MockNeutronClient.
type MockNeutronClientMockRecorder struct {
	mock *MockNeutronClient
}

// NewMockNeutronClient creates a new mock instance.
func NewMockNeutronClient(ctrl *gomock.Controller) *MockNeutronClient {
	mock := &MockNeutronClient{ctrl: ctrl}
	mock.recorder = &MockNeutronClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNeutronClient) EXPECT() *MockNeutronClientMockRecorder {
	return m.recorder
}

// GetSolanaAumContractNextRound mocks base method.
func (m *MockNeutronClient) GetSolanaAumContractNextRound(ctx context.Context) (*neutron.NextRound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSolanaAumContractNextRound", ctx)
	ret0, _ := ret[0].(*neutron.NextRound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSolanaAumContractNextRound indicates an expected call of GetSolanaAumContractNextRound.
func (mr *MockNeutronClientMockRecorder) GetSolanaAumContractNextRound(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSolanaAumContractNextRound", reflect.TypeOf((*MockNeutronClient)(nil).GetSolanaAumContractNextRound), ctx)
}

// SubmitSolanaAumData mocks base method.
func (m *MockNeutronClient) SubmitSolanaAumData(ctx context.Context, data *neutron.SolanaData) (*neutron.NextRound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitSolanaAumData", ctx, data)
	ret0, _ := ret[0].(*neutron.NextRound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitSolanaAumData indicates an expected call of SubmitSolanaAumData.
func (mr *MockNeutronClientMockRecorder) SubmitSolanaAumData(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitSolanaAumData", reflect.TypeOf((*MockNeutronClient)(nil).SubmitSolanaAumData), ctx, data)
}
