// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../messenger/binance/interface.go

// Package mock_binance is a generated GoMock package.
package mock_binance

import (
	context "context"
	reflect "reflect"

	binance "github.com/adshao/go-binance/v2"
	portfolio "github.com/adshao/go-binance/v2/portfolio"
	gomock "github.com/golang/mock/gomock"
	neutron "github.com/structured-org/aum-messenger/pkg/client/neutron"
	solana "github.com/structured-org/aum-messenger/pkg/client/solana"
)

// MockBinanceClient is a mock of BinanceClient interface.
type MockBinanceClient struct {
	ctrl     *gomock.Controller
	recorder *MockBinanceClientMockRecorder
}

// MockBinanceClientMockRecorder is the mock recorder for MockBinanceClient.
type MockBinanceClientMockRecorder struct {
	mock *MockBinanceClient
}

// NewMockBinanceClient creates a new mock instance.
func NewMockBinanceClient(ctrl *gomock.Controller) *MockBinanceClient {
	mock := &MockBinanceClient{ctrl: ctrl}
	mock.recorder = &MockBinanceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBinanceClient) EXPECT() *MockBinanceClientMockRecorder {
	return m.recorder
}

// GetPMAccountBalance mocks base method.
func (m *MockBinanceClient) GetPMAccountBalance(ctx context.Context) ([]*portfolio.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPMAccountBalance", ctx)
	ret0, _ := ret[0].([]*portfolio.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPMAccountBalance indicates an expected call of GetPMAccountBalance.
func (mr *MockBinanceClientMockRecorder) GetPMAccountBalance(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPMAccountBalance", reflect.TypeOf((*MockBinanceClient)(nil).GetPMAccountBalance), ctx)
}

// GetPMAccountInfo mocks base method.
func (m *MockBinanceClient) GetPMAccountInfo(ctx context.Context) (*portfolio.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPMAccountInfo", ctx)
	ret0, _ := ret[0].(*portfolio.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPMAccountInfo indicates an expected call of GetPMAccountInfo.
func (mr *MockBinanceClientMockRecorder) GetPMAccountInfo(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPMAccountInfo", reflect.TypeOf((*MockBinanceClient)(nil).GetPMAccountInfo), ctx)
}

// GetSpotAccountInfo mocks base method.
func (m *MockBinanceClient) GetSpotAccountInfo(ctx context.Context) (*binance.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpotAccountInfo", ctx)
	ret0, _ := ret[0].(*binance.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpotAccountInfo indicates an expected call of GetSpotAccountInfo.
func (mr *MockBinanceClientMockRecorder) GetSpotAccountInfo(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpotAccountInfo", reflect.TypeOf((*MockBinanceClient)(nil).GetSpotAccountInfo), ctx)
}

// GetUmPositions mocks base method.
func (m *MockBinanceClient) GetUmPositions(ctx context.Context) ([]*portfolio.UMPosition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUmPositions", ctx)
	ret0, _ := ret[0].([]*portfolio.UMPosition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUmPositions indicates an expected call of GetUmPositions.
func (mr *MockBinanceClientMockRecorder) GetUmPositions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUmPositions", reflect.TypeOf((*MockBinanceClient)(nil).GetUmPositions), ctx)
}

// MockNeutronAumReceiverClient is a mock of NeutronAumReceiverClient interface.
type MockNeutronAumReceiverClient struct {
	ctrl     *gomock.Controller
	recorder *MockNeutronAumReceiverClientMockRecorder
}

// MockNeutronAumReceiverClientMockRecorder is the mock recorder for MockNeutronAumReceiverClient.
type MockNeutronAumReceiverClientMockRecorder struct {
	mock *MockNeutronAumReceiverClient
}

// NewMockNeutronAumReceiverClient creates a new mock instance.
func NewMockNeutronAumReceiverClient(ctrl *gomock.Controller) *MockNeutronAumReceiverClient {
	mock := &MockNeutronAumReceiverClient{ctrl: ctrl}
	mock.recorder = &MockNeutronAumReceiverClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNeutronAumReceiverClient) EXPECT() *MockNeutronAumReceiverClientMockRecorder {
	return m.recorder
}

// GetBinanceAumReceiverNextRound mocks base method.
func (m *MockNeutronAumReceiverClient) GetBinanceAumReceiverNextRound(ctx context.Context) (*neutron.NextRound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBinanceAumReceiverNextRound", ctx)
	ret0, _ := ret[0].(*neutron.NextRound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBinanceAumReceiverNextRound indicates an expected call of GetBinanceAumReceiverNextRound.
func (mr *MockNeutronAumReceiverClientMockRecorder) GetBinanceAumReceiverNextRound(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBinanceAumReceiverNextRound", reflect.TypeOf((*MockNeutronAumReceiverClient)(nil).GetBinanceAumReceiverNextRound), ctx)
}

// SubmitBinanceAumData mocks base method.
func (m *MockNeutronAumReceiverClient) SubmitBinanceAumData(ctx context.Context, data *neutron.BinanceAumData) (*neutron.NextRound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitBinanceAumData", ctx, data)
	ret0, _ := ret[0].(*neutron.NextRound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitBinanceAumData indicates an expected call of SubmitBinanceAumData.
func (mr *MockNeutronAumReceiverClientMockRecorder) SubmitBinanceAumData(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitBinanceAumData", reflect.TypeOf((*MockNeutronAumReceiverClient)(nil).SubmitBinanceAumData), ctx, data)
}

// MockSolanaAumReceiverClient is a mock of SolanaAumReceiverClient interface.
type MockSolanaAumReceiverClient struct {
	ctrl     *gomock.Controller
	recorder *MockSolanaAumReceiverClientMockRecorder
}

// MockSolanaAumReceiverClientMockRecorder is the mock recorder for MockSolanaAumReceiverClient.
type MockSolanaAumReceiverClientMockRecorder struct {
	mock *MockSolanaAumReceiverClient
}

// NewMockSolanaAumReceiverClient creates a new mock instance.
func NewMockSolanaAumReceiverClient(ctrl *gomock.Controller) *MockSolanaAumReceiverClient {
	mock := &MockSolanaAumReceiverClient{ctrl: ctrl}
	mock.recorder = &MockSolanaAumReceiverClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSolanaAumReceiverClient) EXPECT() *MockSolanaAumReceiverClientMockRecorder {
	return m.recorder
}

// GetBinanceAumReceiverNextRound mocks base method.
func (m *MockSolanaAumReceiverClient) GetBinanceAumReceiverNextRound(ctx context.Context) (*solana.NextRound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBinanceAumReceiverNextRound", ctx)
	ret0, _ := ret[0].(*solana.NextRound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBinanceAumReceiverNextRound indicates an expected call of GetBinanceAumReceiverNextRound.
func (mr *MockSolanaAumReceiverClientMockRecorder) GetBinanceAumReceiverNextRound(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBinanceAumReceiverNextRound", reflect.TypeOf((*MockSolanaAumReceiverClient)(nil).GetBinanceAumReceiverNextRound), ctx)
}

// SubmitBinanceAumData mocks base method.
func (m *MockSolanaAumReceiverClient) SubmitBinanceAumData(ctx context.Context, data *solana.BinanceAumData) (*solana.NextRound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitBinanceAumData", ctx, data)
	ret0, _ := ret[0].(*solana.NextRound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitBinanceAumData indicates an expected call of SubmitBinanceAumData.
func (mr *MockSolanaAumReceiverClientMockRecorder) SubmitBinanceAumData(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitBinanceAumData", reflect.TypeOf((*MockSolanaAumReceiverClient)(nil).SubmitBinanceAumData), ctx, data)
}
