// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../oracle/binance/interface.go

// Package mock_binance is a generated GoMock package.
package mock_binance

import (
	context "context"
	reflect "reflect"

	binance "github.com/adshao/go-binance/v2"
	portfolio "github.com/adshao/go-binance/v2/portfolio"
	gomock "github.com/golang/mock/gomock"
	neutron "github.com/structured-org/aum-oracle/client/neutron"
	solana "github.com/structured-org/aum-oracle/client/solana"
)

// MockBinanceClient is a mock of BinanceClient interface.
type MockBinanceClient struct {
	ctrl     *gomock.Controller
	recorder *MockBinanceClientMockRecorder
}

// MockBinanceClientMockRecorder is the mock recorder for MockBinanceClient.
type MockBinanceClientMockRecorder struct {
	mock *MockBinanceClient
}

// NewMockBinanceClient creates a new mock instance.
func NewMockBinanceClient(ctrl *gomock.Controller) *MockBinanceClient {
	mock := &MockBinanceClient{ctrl: ctrl}
	mock.recorder = &MockBinanceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBinanceClient) EXPECT() *MockBinanceClientMockRecorder {
	return m.recorder
}

// GetPMAccountBalance mocks base method.
func (m *MockBinanceClient) GetPMAccountBalance(ctx context.Context) ([]*portfolio.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPMAccountBalance", ctx)
	ret0, _ := ret[0].([]*portfolio.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPMAccountBalance indicates an expected call of GetPMAccountBalance.
func (mr *MockBinanceClientMockRecorder) GetPMAccountBalance(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPMAccountBalance", reflect.TypeOf((*MockBinanceClient)(nil).GetPMAccountBalance), ctx)
}

// GetPMAccountInfo mocks base method.
func (m *MockBinanceClient) GetPMAccountInfo(ctx context.Context) (*portfolio.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPMAccountInfo", ctx)
	ret0, _ := ret[0].(*portfolio.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPMAccountInfo indicates an expected call of GetPMAccountInfo.
func (mr *MockBinanceClientMockRecorder) GetPMAccountInfo(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPMAccountInfo", reflect.TypeOf((*MockBinanceClient)(nil).GetPMAccountInfo), ctx)
}

// GetSpotAccountInfo mocks base method.
func (m *MockBinanceClient) GetSpotAccountInfo(ctx context.Context) (*binance.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpotAccountInfo", ctx)
	ret0, _ := ret[0].(*binance.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpotAccountInfo indicates an expected call of GetSpotAccountInfo.
func (mr *MockBinanceClientMockRecorder) GetSpotAccountInfo(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpotAccountInfo", reflect.TypeOf((*MockBinanceClient)(nil).GetSpotAccountInfo), ctx)
}

// GetUmPositions mocks base method.
func (m *MockBinanceClient) GetUmPositions(ctx context.Context) ([]*portfolio.UMPosition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUmPositions", ctx)
	ret0, _ := ret[0].([]*portfolio.UMPosition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUmPositions indicates an expected call of GetUmPositions.
func (mr *MockBinanceClientMockRecorder) GetUmPositions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUmPositions", reflect.TypeOf((*MockBinanceClient)(nil).GetUmPositions), ctx)
}

// MockNeutronAumContractClient is a mock of NeutronAumContractClient interface.
type MockNeutronAumContractClient struct {
	ctrl     *gomock.Controller
	recorder *MockNeutronAumContractClientMockRecorder
}

// MockNeutronAumContractClientMockRecorder is the mock recorder for MockNeutronAumContractClient.
type MockNeutronAumContractClientMockRecorder struct {
	mock *MockNeutronAumContractClient
}

// NewMockNeutronAumContractClient creates a new mock instance.
func NewMockNeutronAumContractClient(ctrl *gomock.Controller) *MockNeutronAumContractClient {
	mock := &MockNeutronAumContractClient{ctrl: ctrl}
	mock.recorder = &MockNeutronAumContractClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNeutronAumContractClient) EXPECT() *MockNeutronAumContractClientMockRecorder {
	return m.recorder
}

// GetBinanceAumContractNextRound mocks base method.
func (m *MockNeutronAumContractClient) GetBinanceAumContractNextRound(ctx context.Context) (*neutron.NextRound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBinanceAumContractNextRound", ctx)
	ret0, _ := ret[0].(*neutron.NextRound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBinanceAumContractNextRound indicates an expected call of GetBinanceAumContractNextRound.
func (mr *MockNeutronAumContractClientMockRecorder) GetBinanceAumContractNextRound(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBinanceAumContractNextRound", reflect.TypeOf((*MockNeutronAumContractClient)(nil).GetBinanceAumContractNextRound), ctx)
}

// SubmitBinanceAumData mocks base method.
func (m *MockNeutronAumContractClient) SubmitBinanceAumData(ctx context.Context, data *neutron.BinanceAumData) (*neutron.NextRound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitBinanceAumData", ctx, data)
	ret0, _ := ret[0].(*neutron.NextRound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitBinanceAumData indicates an expected call of SubmitBinanceAumData.
func (mr *MockNeutronAumContractClientMockRecorder) SubmitBinanceAumData(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitBinanceAumData", reflect.TypeOf((*MockNeutronAumContractClient)(nil).SubmitBinanceAumData), ctx, data)
}

// MockSolanaAumContractClient is a mock of SolanaAumContractClient interface.
type MockSolanaAumContractClient struct {
	ctrl     *gomock.Controller
	recorder *MockSolanaAumContractClientMockRecorder
}

// MockSolanaAumContractClientMockRecorder is the mock recorder for MockSolanaAumContractClient.
type MockSolanaAumContractClientMockRecorder struct {
	mock *MockSolanaAumContractClient
}

// NewMockSolanaAumContractClient creates a new mock instance.
func NewMockSolanaAumContractClient(ctrl *gomock.Controller) *MockSolanaAumContractClient {
	mock := &MockSolanaAumContractClient{ctrl: ctrl}
	mock.recorder = &MockSolanaAumContractClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSolanaAumContractClient) EXPECT() *MockSolanaAumContractClientMockRecorder {
	return m.recorder
}

// GetBinanceAumContractNextRound mocks base method.
func (m *MockSolanaAumContractClient) GetBinanceAumContractNextRound(ctx context.Context) (*solana.NextRound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBinanceAumContractNextRound", ctx)
	ret0, _ := ret[0].(*solana.NextRound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBinanceAumContractNextRound indicates an expected call of GetBinanceAumContractNextRound.
func (mr *MockSolanaAumContractClientMockRecorder) GetBinanceAumContractNextRound(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBinanceAumContractNextRound", reflect.TypeOf((*MockSolanaAumContractClient)(nil).GetBinanceAumContractNextRound), ctx)
}

// SubmitBinanceAumData mocks base method.
func (m *MockSolanaAumContractClient) SubmitBinanceAumData(ctx context.Context, data *solana.BinanceAumData) (*solana.NextRound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitBinanceAumData", ctx, data)
	ret0, _ := ret[0].(*solana.NextRound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitBinanceAumData indicates an expected call of SubmitBinanceAumData.
func (mr *MockSolanaAumContractClientMockRecorder) SubmitBinanceAumData(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitBinanceAumData", reflect.TypeOf((*MockSolanaAumContractClient)(nil).SubmitBinanceAumData), ctx, data)
}
