on:
  push:
    branches:
      - '**'

name: tests

jobs:
  clippy:
    name: Actions - clippy
    runs-on: ubicloud-standard-8
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81.0
          components: clippy
          profile: minimal
          override: true
      - run: cargo fetch --verbose
        working-directory: neutron-contracts
      - run: cargo clippy --all --all-targets -- -D warnings
        working-directory: neutron-contracts

  rustfmt:
    name: Actions - rustfmt
    runs-on: ubicloud-standard-8
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81.0
          components: rustfmt
          profile: minimal
          override: true
      - run: cargo fmt -- --check
        working-directory: neutron-contracts

  unit-test:
    name: Actions - unit test
    runs-on: ubicloud-standard-8
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81.0
          profile: minimal
      - run: cargo fetch --verbose
        working-directory: neutron-contracts
      - run: cargo build
        working-directory: neutron-contracts
      - run: cargo test --verbose --all
        working-directory: neutron-contracts
        env:
          RUST_BACKTRACE: 1
